const fs = require('fs');

const keysToAdd = {
  it: `
  challenge: 'Challenge',
  writeCommand: 'Scrivi il comando...',
  executeBtn: 'Esegui',
  nextChallengeBtn: 'Prossima challenge',
  perfectTitle: 'Perfetto!',
  greatTitle: 'Ottimo!',
  keepGoingTitle: 'Continua!',
  levelLabel: 'Livello:',
  closeBtn: 'Chiudi',
  completeCommand: 'Completa il comando:',
  writeHere: 'Scrivi qui...',
  verifyBtn: 'Verifica',
  correctAnswerIs: 'Risposta corretta:',
  showHint: 'Mostra suggerimento',
  notExact: 'Non esatto.',
  answerLabel: 'Risposta:',
  hintBtn: 'Suggerimento',
  correctAnswers: 'corrette',
  streak: 'Streak',
  badges: 'Badge',
  topic: 'Topic',
`,
  en: `
  challenge: 'Challenge',
  writeCommand: 'Type command...',
  executeBtn: 'Execute',
  nextChallengeBtn: 'Next challenge',
  perfectTitle: 'Perfect!',
  greatTitle: 'Great!',
  keepGoingTitle: 'Keep going!',
  levelLabel: 'Level:',
  closeBtn: 'Close',
  completeCommand: 'Complete the command:',
  writeHere: 'Type here...',
  verifyBtn: 'Verify',
  correctAnswerIs: 'Correct answer:',
  showHint: 'Show hint',
  notExact: 'Not exactly.',
  answerLabel: 'Answer:',
  hintBtn: 'Hint',
  correctAnswers: 'correct',
  streak: 'Streak',
  badges: 'Badges',
  topic: 'Topic',
`,
  es: `
  challenge: 'Desafío',
  writeCommand: 'Escribe el comando...',
  executeBtn: 'Ejecutar',
  nextChallengeBtn: 'Siguiente desafío',
  perfectTitle: '¡Perfecto!',
  greatTitle: '¡Genial!',
  keepGoingTitle: '¡Sigue así!',
  levelLabel: 'Nivel:',
  closeBtn: 'Cerrar',
  completeCommand: 'Completa el comando:',
  writeHere: 'Escribe aquí...',
  verifyBtn: 'Verificar',
  correctAnswerIs: 'Respuesta correcta:',
  showHint: 'Mostrar pista',
  notExact: 'No exactamente.',
  answerLabel: 'Respuesta:',
  hintBtn: 'Pista',
  correctAnswers: 'correctas',
  streak: 'Racha',
  badges: 'Insignias',
  topic: 'Tema',
`,
  fr: `
  challenge: 'Défi',
  writeCommand: 'Tapez la commande...',
  executeBtn: 'Exécuter',
  nextChallengeBtn: 'Défi suivant',
  perfectTitle: 'Parfait !',
  greatTitle: 'Super !',
  keepGoingTitle: 'Continuez !',
  levelLabel: 'Niveau :',
  closeBtn: 'Fermer',
  completeCommand: 'Complétez la commande :',
  writeHere: 'Tapez ici...',
  verifyBtn: 'Vérifier',
  correctAnswerIs: 'Bonne réponse :',
  showHint: 'Montrer un indice',
  notExact: 'Pas exactement.',
  answerLabel: 'Réponse :',
  hintBtn: 'Indice',
  correctAnswers: 'correctes',
  streak: 'Série',
  badges: 'Badges',
  topic: 'Thème',
`,
  de: `
  challenge: 'Herausforderung',
  writeCommand: 'Befehl eingeben...',
  executeBtn: 'Ausführen',
  nextChallengeBtn: 'Nächste Herausforderung',
  perfectTitle: 'Perfekt!',
  greatTitle: 'Großartig!',
  keepGoingTitle: 'Weiter so!',
  levelLabel: 'Level:',
  closeBtn: 'Schließen',
  completeCommand: 'Befehl vervollständigen:',
  writeHere: 'Hier tippen...',
  verifyBtn: 'Überprüfen',
  correctAnswerIs: 'Richtige Antwort:',
  showHint: 'Tipp anzeigen',
  notExact: 'Nicht ganz.',
  answerLabel: 'Antwort:',
  hintBtn: 'Tipp',
  correctAnswers: 'richtig',
  streak: 'Serie',
  badges: 'Abzeichen',
  topic: 'Thema',
`,
  pt: `
  challenge: 'Desafio',
  writeCommand: 'Digite o comando...',
  executeBtn: 'Executar',
  nextChallengeBtn: 'Próximo desafio',
  perfectTitle: 'Perfeito!',
  greatTitle: 'Ótimo!',
  keepGoingTitle: 'Continue assim!',
  levelLabel: 'Nível:',
  closeBtn: 'Fechar',
  completeCommand: 'Complete o comando:',
  writeHere: 'Digite aqui...',
  verifyBtn: 'Verificar',
  correctAnswerIs: 'Resposta correta:',
  showHint: 'Mostrar dica',
  notExact: 'Não exatamente.',
  answerLabel: 'Resposta:',
  hintBtn: 'Dica',
  correctAnswers: 'corretas',
  streak: 'Sequência',
  badges: 'Conquistas',
  topic: 'Tópico',
`,
  ru: `
  challenge: 'Испытание',
  writeCommand: 'Введите команду...',
  executeBtn: 'Выполнить',
  nextChallengeBtn: 'Следующее испытание',
  perfectTitle: 'Идеально!',
  greatTitle: 'Отлично!',
  keepGoingTitle: 'Так держать!',
  levelLabel: 'Уровень:',
  closeBtn: 'Закрыть',
  completeCommand: 'Дополните команду:',
  writeHere: 'Введите здесь...',
  verifyBtn: 'Проверить',
  correctAnswerIs: 'Правильный ответ:',
  showHint: 'Показать подсказку',
  notExact: 'Не совсем.',
  answerLabel: 'Ответ:',
  hintBtn: 'Подсказка',
  correctAnswers: 'верно',
  streak: 'Серия',
  badges: 'Значки',
  topic: 'Тема',
`,
  zh: `
  challenge: '挑战',
  writeCommand: '输入命令...',
  executeBtn: '执行',
  nextChallengeBtn: '下一挑战',
  perfectTitle: '完美！',
  greatTitle: '太棒了！',
  keepGoingTitle: '继续保持！',
  levelLabel: '级别：',
  closeBtn: '关闭',
  completeCommand: '完善命令：',
  writeHere: '在此输入...',
  verifyBtn: '验证',
  correctAnswerIs: '正确答案：',
  showHint: '显示提示',
  notExact: '不完全正确。',
  answerLabel: '答案：',
  hintBtn: '提示',
  correctAnswers: '正确',
  streak: '连续天数',
  badges: '徽章',
  topic: '主题',
`
};

for (const [lang, keys] of Object.entries(keysToAdd)) {
  const file = 'src/locales/' + lang + '/ui.js';
  if (!fs.existsSync(file)) continue;
  
  let content = fs.readFileSync(file, 'utf8');
  
  // Clean up any double additions (like the ones we manually added earlier)
  ['streak:', 'badges:', 'topic:'].forEach(k => {
    const rx = new RegExp('^\\\\s*' + k + '.*$', 'gm');
    content = content.replace(rx, '');
  });
  
  // Insert exactly before the last closing brace
  content = content.replace(/}\\s*$/, keys + '\\n}');
  
  fs.writeFileSync(file, content, 'utf8');
  console.log('Updated ' + lang);
}
