const fs = require('fs');
const path = require('path');

const localesPath = path.join(__dirname, 'src', 'locales');
const langs = ['it', 'en', 'es', 'de', 'ru', 'pt', 'fr', 'zh'];

const missingTranslations = {
  it: {
    backToHome: 'Torna alla Home',
    backToDashboard: 'Torna alla Dashboard',
    topicNotFound: 'Topic non trovato',
    lessonNotFound: 'Lezione non trovata',
    examWeight: 'Peso esame:',
    lessonsCount: 'lezioni',
    lessonsCompleted: 'completate',
    lessons: 'Lezioni',
    contentArriving: 'Contenuto in arrivo!',
    contentArrivingDesc: 'Questa lezione sarà disponibile presto con fumetti e contenuti interattivi.',
    redoQuiz: 'Rifai il Quiz',
    startQuiz: 'Inizia il Quiz!',
    questionsCount: 'domande',
    markCompleted: 'Segna come completata',
    backToTopic: 'Torna a {{topic}}',
    endTopic: 'Fine Topic →',
    completedBadge: 'Completata',
    terminalLabel: 'terminale',
  },
  en: {
    backToHome: 'Back to Home',
    backToDashboard: 'Back to Dashboard',
    topicNotFound: 'Topic not found',
    lessonNotFound: 'Lesson not found',
    examWeight: 'Exam weight:',
    lessonsCount: 'lessons',
    lessonsCompleted: 'completed',
    lessons: 'Lessons',
    contentArriving: 'Content coming soon!',
    contentArrivingDesc: 'This lesson will be available soon with comics and interactive content.',
    redoQuiz: 'Redo Quiz',
    startQuiz: 'Start Quiz!',
    questionsCount: 'questions',
    markCompleted: 'Mark as completed',
    backToTopic: 'Back to {{topic}}',
    endTopic: 'End Topic →',
    completedBadge: 'Completed',
    terminalLabel: 'terminal',
  },
  es: {
    backToHome: 'Volver al Inicio',
    backToDashboard: 'Volver al Dashboard',
    topicNotFound: 'Tema no encontrado',
    lessonNotFound: 'Lección no encontrada',
    examWeight: 'Peso del examen:',
    lessonsCount: 'lecciones',
    lessonsCompleted: 'completadas',
    lessons: 'Lecciones',
    contentArriving: '¡Contenido próximamente!',
    contentArrivingDesc: 'Esta lección estará disponible pronto con cómics y contenido interactivo.',
    redoQuiz: 'Rehacer Cuestionario',
    startQuiz: '¡Empezar Cuestionario!',
    questionsCount: 'preguntas',
    markCompleted: 'Marcar como completada',
    backToTopic: 'Volver a {{topic}}',
    endTopic: 'Fin del Tema →',
    completedBadge: 'Completada',
    terminalLabel: 'terminal',
  },
  de: {
    backToHome: 'Zurück zur Startseite',
    backToDashboard: 'Zurück zum Dashboard',
    topicNotFound: 'Thema nicht gefunden',
    lessonNotFound: 'Lektion nicht gefunden',
    examWeight: 'Prüfungsgewicht:',
    lessonsCount: 'Lektionen',
    lessonsCompleted: 'abgeschlossen',
    lessons: 'Lektionen',
    contentArriving: 'Inhalt kommt bald!',
    contentArrivingDesc: 'Diese Lektion wird bald mit Comics und interaktiven Inhalten verfügbar sein.',
    redoQuiz: 'Quiz wiederholen',
    startQuiz: 'Quiz starten!',
    questionsCount: 'Fragen',
    markCompleted: 'Als abgeschlossen markieren',
    backToTopic: 'Zurück zu {{topic}}',
    endTopic: 'Ende des Themas →',
    completedBadge: 'Abgeschlossen',
    terminalLabel: 'Terminal',
  },
  ru: {
    backToHome: 'Вернуться на главную',
    backToDashboard: 'Вернуться на панель',
    topicNotFound: 'Тема не найдена',
    lessonNotFound: 'Урок не найден',
    examWeight: 'Вес на экзамене:',
    lessonsCount: 'уроков',
    lessonsCompleted: 'завершено',
    lessons: 'Уроки',
    contentArriving: 'Контент скоро появится!',
    contentArrivingDesc: 'Этот урок скоро будет доступен с комиксами и интерактивным контентом.',
    redoQuiz: 'Пройти тест заново',
    startQuiz: 'Начать тест!',
    questionsCount: 'вопросов',
    markCompleted: 'Отметить как завершенный',
    backToTopic: 'Вернуться к {{topic}}',
    endTopic: 'Конец темы →',
    completedBadge: 'Завершено',
    terminalLabel: 'терминал',
  },
  pt: {
    backToHome: 'Voltar ao Início',
    backToDashboard: 'Voltar ao Dashboard',
    topicNotFound: 'Tópico não encontrado',
    lessonNotFound: 'Lição não encontrada',
    examWeight: 'Peso no exame:',
    lessonsCount: 'lições',
    lessonsCompleted: 'concluídas',
    lessons: 'Lições',
    contentArriving: 'Conteúdo em breve!',
    contentArrivingDesc: 'Esta lição estará disponível em breve com quadrinhos e conteúdo interativo.',
    redoQuiz: 'Refazer Quiz',
    startQuiz: 'Iniciar Quiz!',
    questionsCount: 'perguntas',
    markCompleted: 'Marcar como concluída',
    backToTopic: 'Voltar para {{topic}}',
    endTopic: 'Fim do Tópico →',
    completedBadge: 'Concluída',
    terminalLabel: 'terminal',
  },
  fr: {
    backToHome: 'Retour à l\'Accueil',
    backToDashboard: 'Retour au Tableau de bord',
    topicNotFound: 'Sujet introuvable',
    lessonNotFound: 'Leçon introuvable',
    examWeight: 'Poids à l\'examen:',
    lessonsCount: 'leçons',
    lessonsCompleted: 'terminées',
    lessons: 'Leçons',
    contentArriving: 'Contenu à venir !',
    contentArrivingDesc: 'Cette leçon sera bientôt disponible avec des bandes dessinées et du contenu interactif.',
    redoQuiz: 'Refaire le Quiz',
    startQuiz: 'Commencer le Quiz !',
    questionsCount: 'questions',
    markCompleted: 'Marquer comme terminée',
    backToTopic: 'Retour à {{topic}}',
    endTopic: 'Fin du Sujet →',
    completedBadge: 'Terminée',
    terminalLabel: 'terminal',
  },
  zh: {
    backToHome: '返回主页',
    backToDashboard: '返回仪表板',
    topicNotFound: '找不到主题',
    lessonNotFound: '找不到课程',
    examWeight: '考试权重：',
    lessonsCount: '课',
    lessonsCompleted: '已完成',
    lessons: '课程',
    contentArriving: '内容即将推出！',
    contentArrivingDesc: '本课程很快将提供漫画和互动内容。',
    redoQuiz: '重做测验',
    startQuiz: '开始测验！',
    questionsCount: '题',
    markCompleted: '标记为已完成',
    backToTopic: '回到 {{topic}}',
    endTopic: '结束主题 →',
    completedBadge: '已完成',
    terminalLabel: '终端',
  }
};

for (const lang of langs) {
  const file = path.join(localesPath, lang, 'ui.js');
  if (fs.existsSync(file)) {
    let content = fs.readFileSync(file, 'utf8');
    const newKeys = Object.entries(missingTranslations[lang] || {}).map(([k, v]) => `  ${k}: '${v.replace(/'/g, "\\'")}',`).join('\n');
    const lastBraceIndex = content.lastIndexOf('}');
    if (lastBraceIndex !== -1 && newKeys.length > 0) {
      content = content.substring(0, lastBraceIndex) + `\n  // Nuove traduzioni UI Part 2\n${newKeys}\n` + content.substring(lastBraceIndex);
      fs.writeFileSync(file, content);
      console.log(`Updated ${lang}/ui.js`);
    } else {
      console.log(`Skipped ${lang}/ui.js`);
    }
  }
}
