const fs = require('fs');
const path = require('path');

const localesPath = path.join(__dirname, 'src', 'locales');
const langs = ['it', 'en', 'es', 'de', 'ru', 'pt', 'fr', 'zh'];

const missingTranslations = {
  it: {
    playAndLearn: 'Gioca & Impara',
    playAndLearnDesc: 'Quiz, Memory, Terminal Challenge...',
    examSimDesc: 'Miglior punteggio: {{score}}/800',
    examSimFallback: '40 domande • 60 minuti',
    the5Topics: "I 5 Topic dell'Esame",
    weight: 'Peso:',
    lessonsProgress: 'lezioni',
    review: 'Rivedi',
    continue: 'Continua',
    levelX: 'Livello {{level}}',
    quizDesc: 'Metti alla prova le tue conoscenze con quiz a scelta multipla da tutti i topic.',
    memoryDesc: 'Abbina comandi Linux alle loro descrizioni. Allena la tua memoria!',
    terminalDesc: 'Scrivi il comando giusto! Come un vero sysadmin!',
    dragdropDesc: 'Associa concetti: licenze, permessi, porte di rete e altro!',
    fillgapDesc: 'Riempi gli spazi vuoti nei comandi Linux. Fill-the-gap!',
    truefalseDesc: 'Rispondi il più velocemente possibile: è vero o falso? Hai 10 secondi!',
    level1Desc: 'Contenuto base, tempo rilassato',
    level2Desc: 'Più contenuti, parametri sfidanti',
    level3Desc: 'Tutto il contenuto, massima difficoltà',
    passedTitle: 'PROMOSSO!',
    notYetTitle: 'Non ancora...',
    correctAnswers: 'risposte corrette',
    minToPass1: 'Minimo 500/800',
    minToPass2: 'Servono 500/800 per passare',
    timeLabel: 'Tempo:',
    resultsByTopic: 'Risultati per Topic',
    reviewAnswers: 'Revisione Risposte',
    retryBtn: 'Riprova',
    explanation: 'Spiegazione:',
    nextBtn: 'Prossima',
    seeResultsBtn: 'Vedi Risultati',
    questionNum: 'Domanda',
    correctBadge: 'corrette',
    examRules: "Regole dell'Esame",
    examWarningTitle: 'Attenzione',
    examWarningText: 'Le domande sono randomizzate dal pool di {{total}} domande. Il timer parte appena inizi!',
  },
  en: {
    playAndLearn: 'Play & Learn',
    playAndLearnDesc: 'Quiz, Memory, Terminal Challenge...',
    examSimDesc: 'Best score: {{score}}/800',
    examSimFallback: '40 questions • 60 minutes',
    the5Topics: "The 5 Exam Topics",
    weight: 'Weight:',
    lessonsProgress: 'lessons',
    review: 'Review',
    continue: 'Continue',
    levelX: 'Level {{level}}',
    quizDesc: 'Test your knowledge with multiple choice quizzes from all topics.',
    memoryDesc: 'Match Linux commands to their descriptions. Train your memory!',
    terminalDesc: 'Type the right command! Like a real sysadmin!',
    dragdropDesc: 'Associate concepts: licenses, permissions, network ports and more!',
    fillgapDesc: 'Fill in the blanks in Linux commands. Fill-the-gap!',
    truefalseDesc: 'Answer as fast as possible: true or false? You have 10 seconds!',
    level1Desc: 'Basic content, relaxed time',
    level2Desc: 'More content, challenging parameters',
    level3Desc: 'All content, maximum difficulty',
    passedTitle: 'PASSED!',
    notYetTitle: 'Not yet...',
    correctAnswers: 'correct answers',
    minToPass1: 'Minimum 500/800',
    minToPass2: 'Need 500/800 to pass',
    timeLabel: 'Time:',
    resultsByTopic: 'Results by Topic',
    reviewAnswers: 'Review Answers',
    retryBtn: 'Retry',
    explanation: 'Explanation:',
    nextBtn: 'Next',
    seeResultsBtn: 'See Results',
    questionNum: 'Question',
    correctBadge: 'correct',
    examRules: "Exam Rules",
    examWarningTitle: 'Warning',
    examWarningText: 'Questions are randomized from a pool of {{total}} questions. The timer starts when you begin!',
  },
  es: {
    playAndLearn: 'Juega y Aprende',
    playAndLearnDesc: 'Quiz, Memoria, Terminal Challenge...',
    examSimDesc: 'Mejor puntuación: {{score}}/800',
    examSimFallback: '40 preguntas • 60 minutos',
    the5Topics: "Los 5 Temas del Examen",
    weight: 'Peso:',
    lessonsProgress: 'lecciones',
    review: 'Revisar',
    continue: 'Continuar',
    levelX: 'Nivel {{level}}',
    quizDesc: 'Pon a prueba tus conocimientos con cuestionarios de opción múltiple de todos los temas.',
    memoryDesc: 'Empareja los comandos de Linux con sus descripciones. ¡Entrena tu memoria!',
    terminalDesc: '¡Escribe el comando correcto! ¡Como un verdadero administrador de sistemas!',
    dragdropDesc: 'Asocia conceptos: licencias, permisos, puertos de red y más.',
    fillgapDesc: 'Rellena los espacios en blanco en los comandos de Linux. ¡Fill-the-gap!',
    truefalseDesc: 'Responde lo más rápido posible: ¿verdadero o falso? ¡Tienes 10 segundos!',
    level1Desc: 'Contenido básico, tiempo relajado',
    level2Desc: 'Más contenido, parámetros desafiantes',
    level3Desc: 'Todo el contenido, máxima dificultad',
    passedTitle: '¡APROBADO!',
    notYetTitle: 'Todavía no...',
    correctAnswers: 'respuestas correctas',
    minToPass1: 'Mínimo 500/800',
    minToPass2: 'Se necesitan 500/800 para aprobar',
    timeLabel: 'Tiempo:',
    resultsByTopic: 'Resultados por Tema',
    reviewAnswers: 'Revisar Respuestas',
    retryBtn: 'Reintentar',
    explanation: 'Explicación:',
    nextBtn: 'Siguiente',
    seeResultsBtn: 'Ver Resultados',
    questionNum: 'Pregunta',
    correctBadge: 'correctas',
    examRules: "Reglas del Examen",
    examWarningTitle: 'Atención',
    examWarningText: 'Las preguntas son aleatorias de un grupo de {{total}} preguntas. ¡El temporizador comienza al iniciar!',
  },
  de: {
    playAndLearn: 'Spielen & Lernen',
    playAndLearnDesc: 'Quiz, Memory, Terminal Challenge...',
    examSimDesc: 'Beste Punktzahl: {{score}}/800',
    examSimFallback: '40 Fragen • 60 Minuten',
    the5Topics: "Die 5 Prüfungsthemen",
    weight: 'Gewicht:',
    lessonsProgress: 'Lektionen',
    review: 'Überprüfen',
    continue: 'Fortsetzen',
    levelX: 'Stufe {{level}}',
    quizDesc: 'Testen Sie Ihr Wissen mit Multiple-Choice-Quizzen aus allen Themenbereichen.',
    memoryDesc: 'Ordnen Sie Linux-Befehle ihren Beschreibungen zu. Trainieren Sie Ihr Gedächtnis!',
    terminalDesc: 'Geben Sie den richtigen Befehl ein! Wie ein echter Sysadmin!',
    dragdropDesc: 'Verknüpfen Sie Konzepte: Lizenzen, Berechtigungen, Netzwerkports und mehr!',
    fillgapDesc: 'Füllen Sie die Lücken in Linux-Befehlen aus. Fill-the-gap!',
    truefalseDesc: 'Antworten Sie so schnell wie möglich: wahr oder falsch? Sie haben 10 Sekunden!',
    level1Desc: 'Grundlegender Inhalt, entspannte Zeit',
    level2Desc: 'Mehr Inhalt, herausfordernde Parameter',
    level3Desc: 'Gesamter Inhalt, maximale Schwierigkeit',
    passedTitle: 'BESTANDEN!',
    notYetTitle: 'Noch nicht...',
    correctAnswers: 'richtige Antworten',
    minToPass1: 'Minimum 500/800',
    minToPass2: '500/800 zum Bestehen benötigt',
    timeLabel: 'Zeit:',
    resultsByTopic: 'Ergebnisse nach Thema',
    reviewAnswers: 'Antworten überprüfen',
    retryBtn: 'Wiederholen',
    explanation: 'Erklärung:',
    nextBtn: 'Weiter',
    seeResultsBtn: 'Ergebnisse ansehen',
    questionNum: 'Frage',
    correctBadge: 'richtig',
    examRules: "Prüfungsregeln",
    examWarningTitle: 'Achtung',
    examWarningText: 'Die Fragen werden zufällig aus einem Pool von {{total}} Fragen ausgewählt. Der Timer startet sofort!',
  },
  ru: {
    playAndLearn: 'Играй и Учись',
    playAndLearnDesc: 'Викторина, Память, Терминал...',
    examSimDesc: 'Лучший результат: {{score}}/800',
    examSimFallback: '40 вопросов • 60 минут',
    the5Topics: "5 Тем Экзамена",
    weight: 'Вес:',
    lessonsProgress: 'уроков',
    review: 'Обзор',
    continue: 'Продолжить',
    levelX: 'Уровень {{level}}',
    quizDesc: 'Проверьте свои знания с помощью тестов со множественным выбором по всем темам.',
    memoryDesc: 'Сопоставьте команды Linux с их описанием. Тренируйте память!',
    terminalDesc: 'Введите правильную команду! Как настоящий сисадмин!',
    dragdropDesc: 'Свяжите понятия: лицензии, права доступа, сетевые порты и многое другое!',
    fillgapDesc: 'Заполните пропуски в командах Linux. Fill-the-gap!',
    truefalseDesc: 'Отвечайте как можно быстрее: правда или ложь? У вас 10 секунд!',
    level1Desc: 'Базовый контент, расслабленное время',
    level2Desc: 'Больше контента, сложные параметры',
    level3Desc: 'Весь контент, максимальная сложность',
    passedTitle: 'СДАНО!',
    notYetTitle: 'Пока нет...',
    correctAnswers: 'правильных ответов',
    minToPass1: 'Минимум 500/800',
    minToPass2: 'Нужно 500/800 для сдачи',
    timeLabel: 'Время:',
    resultsByTopic: 'Результаты по темам',
    reviewAnswers: 'Обзор ответов',
    retryBtn: 'Повторить',
    explanation: 'Объяснение:',
    nextBtn: 'Далее',
    seeResultsBtn: 'Смотреть результаты',
    questionNum: 'Вопрос',
    correctBadge: 'верно',
    examRules: "Правила экзамена",
    examWarningTitle: 'Внимание',
    examWarningText: 'Вопросы случайным образом выбираются из пула в {{total}} вопросов. Таймер запускается сразу!',
  },
  pt: {
    playAndLearn: 'Jogar e Aprender',
    playAndLearnDesc: 'Quiz, Memória, Desafio Terminal...',
    examSimDesc: 'Melhor pontuação: {{score}}/800',
    examSimFallback: '40 perguntas • 60 minutos',
    the5Topics: "Os 5 Tópicos do Exame",
    weight: 'Peso:',
    lessonsProgress: 'lições',
    review: 'Revisar',
    continue: 'Continuar',
    levelX: 'Nível {{level}}',
    quizDesc: 'Teste seus conhecimentos com questionários de múltipla escolha de todos os tópicos.',
    memoryDesc: 'Combine comandos do Linux com suas descrições. Treine sua memória!',
    terminalDesc: 'Digite o comando certo! Como um verdadeiro sysadmin!',
    dragdropDesc: 'Associe conceitos: licenças, permissões, portas de rede e muito mais!',
    fillgapDesc: 'Preencha as lacunas nos comandos do Linux. Fill-the-gap!',
    truefalseDesc: 'Responda o mais rápido possível: verdadeiro ou falso? Você tem 10 segundos!',
    level1Desc: 'Conteúdo básico, tempo relaxado',
    level2Desc: 'Mais conteúdo, parâmetros desafiadores',
    level3Desc: 'Todo o conteúdo, dificuldade máxima',
    passedTitle: 'APROVADO!',
    notYetTitle: 'Ainda não...',
    correctAnswers: 'respostas corretas',
    minToPass1: 'Mínimo 500/800',
    minToPass2: 'Precisa de 500/800 para passar',
    timeLabel: 'Tempo:',
    resultsByTopic: 'Resultados por Tópico',
    reviewAnswers: 'Revisar Respostas',
    retryBtn: 'Repetir',
    explanation: 'Explicação:',
    nextBtn: 'Próxima',
    seeResultsBtn: 'Ver Resultados',
    questionNum: 'Pergunta',
    correctBadge: 'corretas',
    examRules: "Regras do Exame",
    examWarningTitle: 'Atenção',
    examWarningText: 'As perguntas são escolhidas aleatoriamente de um grupo de {{total}} perguntas. O cronômetro começa ao iniciar!',
  },
  fr: {
    playAndLearn: 'Jouer et Apprendre',
    playAndLearnDesc: 'Quiz, Mémoire, Défi Terminal...',
    examSimDesc: 'Meilleur score : {{score}}/800',
    examSimFallback: '40 questions • 60 minutes',
    the5Topics: "Les 5 Sujets de l'Examen",
    weight: 'Poids :',
    lessonsProgress: 'leçons',
    review: 'Réviser',
    continue: 'Continuer',
    levelX: 'Niveau {{level}}',
    quizDesc: 'Testez vos connaissances avec des quiz à choix multiples sur tous les sujets.',
    memoryDesc: 'Associez les commandes Linux à leurs descriptions. Entraînez votre mémoire !',
    terminalDesc: 'Tapez la bonne commande ! Comme un vrai sysadmin !',
    dragdropDesc: 'Associez les concepts : licences, permissions, ports réseau et plus !',
    fillgapDesc: 'Remplissez les blancs dans les commandes Linux. Fill-the-gap !',
    truefalseDesc: 'Répondez le plus vite possible : vrai ou faux ? Vous avez 10 secondes !',
    level1Desc: 'Contenu de base, temps détendu',
    level2Desc: 'Plus de contenu, paramètres stimulants',
    level3Desc: 'Tout le contenu, difficulté maximale',
    passedTitle: 'RÉUSSI !',
    notYetTitle: 'Pas encore...',
    correctAnswers: 'réponses correctes',
    minToPass1: 'Minimum 500/800',
    minToPass2: 'Il faut 500/800 pour réussir',
    timeLabel: 'Temps :',
    resultsByTopic: 'Résultats par Sujet',
    reviewAnswers: 'Revoir les Réponses',
    retryBtn: 'Réessayer',
    explanation: 'Explication :',
    nextBtn: 'Suivante',
    seeResultsBtn: 'Voir les Résultats',
    questionNum: 'Question',
    correctBadge: 'correctes',
    examRules: "Règles de l'Examen",
    examWarningTitle: 'Attention',
    examWarningText: 'Les questions sont tirées au hasard parmi une banque de {{total}} questions. Le chrono démarre dès le début !',
  },
  zh: {
    playAndLearn: '边玩边学',
    playAndLearnDesc: '测验、记忆、终端挑战...',
    examSimDesc: '最高分：{{score}}/800',
    examSimFallback: '40 个问题 • 60 分钟',
    the5Topics: "5 个考试主题",
    weight: '权重：',
    lessonsProgress: '节课',
    review: '复习',
    continue: '继续',
    levelX: '等级 {{level}}',
    quizDesc: '通过涵盖所有主题的多项选择题测试您的知识。',
    memoryDesc: '将 Linux 命令与其描述匹配。训练您的记忆力！',
    terminalDesc: '输入正确的命令！就像个真正的系统管理员！',
    dragdropDesc: '关联概念：许可证、权限、网络端口等！',
    fillgapDesc: '填补 Linux 命令中的空白。填空题！',
    truefalseDesc: '尽可能快地回答：真或假？您有 10 秒钟时间！',
    level1Desc: '基础内容，充足时间',
    level2Desc: '更多内容，挑战性参数',
    level3Desc: '所有内容，最高难度',
    passedTitle: '通过！',
    notYetTitle: '还没...',
    correctAnswers: '正确答案',
    minToPass1: '最低 500/800',
    minToPass2: '需要 500/800 才能通过',
    timeLabel: '时间：',
    resultsByTopic: '按主题分列的结果',
    reviewAnswers: '查看答案',
    retryBtn: '重试',
    explanation: '解释：',
    nextBtn: '下一题',
    seeResultsBtn: '查看结果',
    questionNum: '问题',
    correctBadge: '正确',
    examRules: "考试规则",
    examWarningTitle: '警告',
    examWarningText: '问题从包含 {{total}} 个问题的题库中随机抽取。计时器在您开始时即启动！',
  }
};

for (const lang of langs) {
  const file = path.join(localesPath, lang, 'ui.js');
  if (fs.existsSync(file)) {
    let content = fs.readFileSync(file, 'utf8');
    const newKeys = Object.entries(missingTranslations[lang] || {}).map(([k, v]) => `  ${k}: '${v.replace(/'/g, "\\'")}',`).join('\n');
    const lastBraceIndex = content.lastIndexOf('}');
    if (lastBraceIndex !== -1 && newKeys.length > 0) {
      content = content.substring(0, lastBraceIndex) + `\n  // Nuove traduzioni UI\n${newKeys}\n` + content.substring(lastBraceIndex);
      fs.writeFileSync(file, content);
      console.log(`Updated ${lang}/ui.js`);
    } else {
      console.log(`Skipped ${lang}/ui.js`);
    }
  }
}
